In [ ]:
A = [1,2,3,4,5,6]
B = [13, 21, 34]

In [ ]:
print(A.append(B))

None


In [ ]:
print(A.extend(B))

None


In [ ]:
import numpy as np

In [ ]:
print(np.array[(1,0,0),(0,1,0),(0,0,1)])

TypeError: ignored

In [ ]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print(np.array([1,0,0],[0,1,0],[0,0,1]))

TypeError: ignored

In [ ]:
import pandas as pd

In [ ]:
url = "https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv"
fuel_data = pd.read_csv(url,error_bad_lines=False)
fuel_data.describe(include="all")

record_id  ...  fuel_cost_per_mmbtu
count                      29523  ...         29523.000000
unique                     29523  ...                  NaN
top     f1_fuel_2017_12_134_1_14  ...                  NaN
freq                           1  ...                  NaN
mean                         NaN  ...            19.304354
std                          NaN  ...          2091.540939
min                          NaN  ...           -41.501000
25%                          NaN  ...             1.940000
50%                          NaN  ...             4.127000
75%                          NaN  ...             7.745000
max                          NaN  ...        359278.000000

[11 rows x 11 columns]

In [ ]:
fuel_data.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64