In [ ]:
# importing labraries
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("Data_for_UCI_named.csv")

In [ ]:
print(df)

          tau1      tau2      tau3  ...        g4      stab     stabf
0     2.959060  3.079885  8.381025  ...  0.958034  0.055347  unstable
1     9.304097  4.902524  3.047541  ...  0.781760 -0.005957    stable
2     8.971707  8.848428  3.046479  ...  0.109853  0.003471  unstable
3     0.716415  7.669600  4.486641  ...  0.362718  0.028871  unstable
4     3.134112  7.608772  4.943759  ...  0.820923  0.049860  unstable
...        ...       ...       ...  ...       ...       ...       ...
9995  2.930406  9.487627  2.376523  ...  0.608385  0.023892  unstable
9996  3.392299  1.274827  2.954947  ...  0.366120 -0.025803    stable
9997  2.364034  2.842030  8.776391  ...  0.145984 -0.031810    stable
9998  9.631511  3.994398  2.757071  ...  0.818391  0.037789  unstable
9999  6.530527  6.781790  4.349695  ...  0.942631  0.045263  unstable

[10000 rows x 14 columns]


In [ ]:
x = df.iloc[:, :-2].values
y = df.iloc[:, -1].values

In [ ]:
print(x)

[[2.95906002 3.0798852  8.38102539 ... 0.85957811 0.88744492 0.95803399]
 [9.30409723 4.90252411 3.04754073 ... 0.86241408 0.56213905 0.78175991]
 [8.97170691 8.84842842 3.04647875 ... 0.76668866 0.83944402 0.10985324]
 ...
 [2.36403419 2.84203025 8.77639096 ... 0.98650532 0.14928646 0.14598403]
 [9.63151069 3.9943976  2.75707093 ... 0.58755755 0.88911835 0.81839133]
 [6.53052662 6.7817899  4.34969522 ... 0.50544105 0.37876093 0.94263083]]


In [ ]:
print(y)

['unstable' 'stable' 'unstable' ... 'stable' 'unstable' 'unstable']


In [ ]:
# splitting the dataset into training set and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [ ]:
# Standard Scaler
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [87]:
# Train a random forest classifier
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
rfc.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=1, verbose=0,
                       warm_start=False)

In [98]:
y_pred = rfc.predict(x_test)

In [99]:
# Check accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9265

In [77]:
# Train XGBoost Model
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [100]:
y_pred1 = xgb.predict(x_test)

In [101]:
# Check accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred1)

0.9195

In [84]:
# build the lightgbm model
import lightgbm as lgb
clf = lgb.LGBMClassifier()
clf.fit(x_train, y_train)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [96]:
y_predicted = clf.predict(x_test)

In [97]:
# Check accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_predicted)

0.9375

In [90]:
from sklearn.tree import ExtraTreeClassifier
etc = ExtraTreeClassifier()
etc.fit(x_train, y_train)

ExtraTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                    max_depth=None, max_features='auto', max_leaf_nodes=None,
                    min_impurity_decrease=0.0, min_impurity_split=None,
                    min_samples_leaf=1, min_samples_split=2,
                    min_weight_fraction_leaf=0.0, random_state=None,
                    splitter='random')

In [94]:
y_pred2 = etc.predict(x_test)

In [95]:
# Check accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred2)

0.7395

In [105]:
# Randomized Cross Validation Search
from sklearn.model_selection import RandomizedSearchCV 
est = RandomForestClassifier(n_jobs=-1)
n_estimators = [50, 100, 300, 500, 1000]
min_samples_split = [2, 3, 5, 7, 9]
min_samples_leaf = [1, 2, 4, 6, 8]
max_features = ['auto', 'sqrt', 'log2', None]
hyperparameter_grid = {'n_estimators': n_estimators,
                       'min_samples_leaf': min_samples_leaf,
                       'min_samples_split': min_samples_split,
                       'max_features': max_features}
random_search = RandomizedSearchCV(est, param_distributions=hyperparameter_grid, n_iter=10, n_jobs=-1, cv=8)
random_search.fit(x_train, y_train)
random_search.best_params_

{'max_features': 'sqrt',
 'min_samples_leaf': 2,
 'min_samples_split': 7,
 'n_estimators': 500}

In [102]:
from sklearn.tree import ExtraTreeClassifier
etc = ExtraTreeClassifier(max_features='sqrt', min_samples_leaf= 1, min_samples_split= 7)
etc.fit(x_train, y_train)

ExtraTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                    max_depth=None, max_features='sqrt', max_leaf_nodes=None,
                    min_impurity_decrease=0.0, min_impurity_split=None,
                    min_samples_leaf=1, min_samples_split=7,
                    min_weight_fraction_leaf=0.0, random_state=None,
                    splitter='random')

In [103]:
y_future = etc.predict(x_test)

In [104]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_future)

0.774

In [71]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(max_features='sqrt', min_samples_leaf= 1, min_samples_split= 7, n_estimators= 300)
classifier.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=7,
                       min_weight_fraction_leaf=0.0, n_estimators=300,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [72]:
y_predict = classifier.predict(x_test)

In [73]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_predict)

0.925